CREATE TABLE usuarios (
    nome VARCHAR(100),
    email VARCHAR(100),
    idade INT
);

INSERT INTO 
    usuarios(nome, email, idade) 
VALUES 
    ("Carlos Pereira", "carlos.pereira@email.com", 42),
    ("Mariana Costa", "mariana.costa@gmail.com", 27),
    ("João Oliveira", "joao.oliveira@yahoo.com", 38),
    ("Fernanda Souza", "fernanda.souza@outlook.com", 33),
    ("Thiago Lima", "thiago.lima@gmail.com", 29),
    ("Patrícia Rocha", "patricia.rocha@hotmail.com", 41),
    ("Bruno Martins", "bruno.martins@email.com", 36),
    ("Aline Gomes", "aline.gomes@gmail.com", 25),
    ("Ricardo Almeida", "ricardo.almeida@outlook.com", 50),
    ("Juliana Mendes", "juliana.mendes@yahoo.com", 34),
    ("Gabriel Nunes", "gabriel.nunes@gmail.com", 31),
    ("Camila Teixeira", "camila.teixeira@outlook.com", 28),
    ("Lucas Fernandes", "lucas.fernandes@email.com", 40),
    ("Vanessa Moraes", "vanessa.moraes@gmail.com", 37),
    ("Daniel Ribeiro", "daniel.ribeiro@hotmail.com", 43),
    ("Larissa Barros", "larissa.barros@gmail.com", 26),
    ("Rafael Castro", "rafael.castro@outlook.com", 32),
    ("Beatriz Carvalho", "beatriz.carvalho@yahoo.com", 29),
    ("Diego Lopes", "diego.lopes@gmail.com", 35),
    ("Renata Azevedo", "renata.azevedo@outlook.com", 39),
    ("Eduardo Pinto", "eduardo.pinto@email.com", 48),
    ("Isabela Farias", "isabela.farias@gmail.com", 30),
    ("André Cunha", "andre.cunha@outlook.com", 45),
    ("Tainá Dias", "taina.dias@gmail.com", 27),
    ("Felipe Rezende", "felipe.rezende@outlook.com", 31),
    ("Natália Campos", "natalia.campos@yahoo.com", 33),
    ("Marcelo Vieira", "marcelo.vieira@gmail.com", 44),
    ("Bruna Andrade", "bruna.andrade@outlook.com", 36),
    ("Leandro Meireles", "leandro.meireles@email.com", 42),
    ("Sabrina Ferreira", "sabrina.ferreira@gmail.com", 25),
    ("Igor Rocha", "igor.rocha@outlook.com", 38),
    ("Tatiane Lima", "tatiane.lima@hotmail.com", 34),
    ("Pedro Cardoso", "pedro.cardoso@gmail.com", 29),
    ("Luana Reis", "luana.reis@outlook.com", 30),
    ("Otávio Martins", "otavio.martins@email.com", 47),
    ("Elaine Barbosa", "elaine.barbosa@gmail.com", 41),
    ("Fábio Souza", "fabio.souza@outlook.com", 46),
    ("Adriana Rocha", "adriana.rocha@yahoo.com", 32),
    ("Henrique Duarte", "henrique.duarte@gmail.com", 39),
    ("Paula Neves", "paula.neves@outlook.com", 28),
    ("Murilo Tavares", "murilo.tavares@gmail.com", 35),
    ("Mirella Vasconcelos", "mirella.vasconcelos@outlook.com", 30),
    ("Otília Mendes", "otilia.mendes@gmail.com", 49),
    ("César Borges", "cesar.borges@email.com", 52),
    ("Jéssica Ramos", "jessica.ramos@outlook.com", 27),
    ("Matheus Monteiro", "matheus.monteiro@gmail.com", 33);